### PR TITLE
dashes -> empty lines

### PR DESCRIPTION
**Pull request by calvinmetcalf**
This is based off the fork I've had for a while that converts all `<p></p>` tags to `<div></div>` , modified to also do `<h[0-9])</h[0-9]>` tags. Upside is even easier to type, downside is no easy way to do lists.

### CODE REVIEW

**Comment by tmcw** [comment]
Yeah, I prefer a cleaner abstraction here - it should be simple to add lists and multi-line text. Tried this out earlier and it's a bit too magic.

**Comment by calvinmetcalf** [comment]
Lists can easily be put in here, the issues is lists that have headers lines and multiline text.  As a serious question do you find yourself using those features very often in presentations with big, if you or other do then that is a good trade-off, but the only place I've seen line breaks used in a big presentations is your project-it-yourself one.

Definitely too much magic for big, but for biggie?

**Comment by tmcw** [comment]
I use linebreaks for hinting word wrapping - basically 'adding a br' and so on. The real question is whether it's useful to sacrifice clarity for brevity: I would rather have a 'hard rule' that anything between `---` is always markdown than save three chars of typing for the caveat that some things you can do in markdown you can't do in biggie.

(that said, `---` no longer means `<hr>` but that's workaroundable and I don't see people using that construct often)

**Comment by calvinmetcalf** [comment]
a more intuitive one might be single line break for hinting and two for new slide

**Comment by tmcw** [comment]
Still seems too magic - people are not used to having special meaning in whitespace.

**Pull request closed without merging**
